#
# This zone library consists of both a public API, and generation
# code based on proc macros. The procedural macro is not part
# of the public API.
#
[workspace]
members = ["zone", "zone_cfg_derive" ]
default-members = ["zone", "zone_cfg_derive" ]
