#
# Configuration for GitHub-based CI, based on the stock GitHub Rust config.
#
name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
    # actions/checkout@v2
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - uses: actions-rs/toolchain@88dc2356392166efad76775c878094f4e83ff746
      with:
        toolchain: stable
        default: false
        components: rustfmt
    - name: Check style
      run: cargo fmt -- --check

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
    # actions/checkout@v2
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Build
      run: cargo build --tests --verbose
    - name: Run tests
      run: cargo test --verbose
